### ISSUE TITLE
Wont continue over night

### ISSUE THREAD

**Issue by Downwrghty** [AbrasiveTax49/Crunchyroll-Account-Checker#1]
valueerror: too many values to unpack (expected 2) fix

any fix?

**Comment by IRdotAI** [comment]
https://github.com/IRdotAI/Crunchyroll-config/releases/tag/v.2.0.2
or
https://github.com/IRdotAI/Rhax-AIO/releases/tag/v.1.0.6

**Comment by IRdotAI** [comment]
This project is no longer getting updates as i made new and improved ones.
